# Generated by Django 3.1.1 on 2020-09-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogposts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('heading', models.CharField(default='', max_length=50)),
                ('cheading', models.CharField(default='', max_length=5000)),
                ('subheading1', models.CharField(default='', max_length=50)),
                ('cheading1', models.CharField(default='', max_length=5000)),
                ('subheading2', models.CharField(default='', max_length=50)),
                ('cheading2', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Blogpost',
        ),
    ]
