# Generated by Django 3.1.1 on 2020-09-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200917_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
