# Generated by Django 3.1.1 on 2020-09-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200919_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='region',
            field=models.CharField(default='World', max_length=50),
        ),
    ]
