# Generated by Django 3.1.1 on 2020-09-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200922_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
        migrations.AddField(
            model_name='orders',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
